// WiFi settings
#define SSID "SSID"
#define PWD "PASSWORD"

// Select your ESP model
//#define CAMERA_MODEL_WROVER_KIT
//#define CAMERA_MODEL_ESP_EYE
//#define CAMERA_MODEL_M5STACK_PSRAM
//#define CAMERA_MODEL_M5STACK_WIDE
//#define CAMERA_MODEL_AI_THINKER

// Select RESOLUTION of stream
//#define RESOLUTION FRAMESIZE_QQVGA;    // 160x120
//#define RESOLUTION FRAMESIZE_QQVGA2;   // 128x160
//#define RESOLUTION FRAMESIZE_QCIF;     // 176x144
//#define RESOLUTION FRAMESIZE_HQVGA;    // 240x176
//#define RESOLUTION FRAMESIZE_QVGA;     // 320x240
//#define RESOLUTION FRAMESIZE_CIF;      // 400x296
//#define RESOLUTION FRAMESIZE_VGA;      // 640x480
//#define RESOLUTION FRAMESIZE_SVGA;     // 800x600
//#define RESOLUTION FRAMESIZE_XGA;      // 1024x768
//#define RESOLUTION FRAMESIZE_SXGA;     // 1280x1024
//#define RESOLUTION FRAMESIZE_UXGA;     // 1600x1200
//#define RESOLUTION FRAMESIZE_QXGA;     // 2048*1536

// Select framerate
#define FPS 14